trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmResourceGroupName: 'Firstresource'
    backendAzureRmStorageAccountName: 'tstateterraform01'
    backendAzureRmContainerName: 'tfstate'  
