# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformCLI@0
  displayName: Terraform Init
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'Free Trial (06a981a6-ce1c-421e-a6e8-431e5dcd12af)'
    allowTelemetryCollection: true

#- task: TerraformCLI@0
#  displayName: Terraform Plan
#  inputs:
#    command: 'plan'
#    environmentServiceName: 'Free Trial (06a981a6-ce1c-421e-a6e8-431e5dcd12af)'
#    allowTelemetryCollection: false

#- task: TerraformCLI@0
#  displayName: Terraform apply
#  inputs:
#    command: 'apply'
#    environmentServiceName: 'Free Trial (06a981a6-ce1c-421e-a6e8-431e5dcd12af)'
#    allowTelemetryCollection: true

- task: TerraformCLI@0
  displayName: Terraform Destroy
  inputs:
    command: 'destroy'
    environmentServiceName: 'Free Trial (06a981a6-ce1c-421e-a6e8-431e5dcd12af)'
    allowTelemetryCollection: true