trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'Azure subscription 1(0e5b585e-4de9-411c-8794-f1128451b880)'
    backendAzureRmResourceGroupName: 'visal-resource-group'
    backendAzureRmStorageAccountName: 'visalstorage'
    backendAzureRmContainerName: 'visalcontainer'
    backendAzureRmKey: 'terraform1.tfstate'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'Azure subscription 1(0e5b585e-4de9-411c-8794-f1128451b880)'
  - task: TerraformTaskV4@4
    inputs:
      provider: 'azurerm'
      command: 'apply'
    commandOptions: '-var="client_id=$(client_id)" -var="client_secret=$(client_secret)" -var="subscription_id=$(subscription_id)" -var="tenant_id=$(tenant_id)"'
    #commandOptions: '-var="client_id=$(client_id)" -var="subscription_id=$(subscription_id)" " -var="tenant_id=$(tenant_id)" -var="client_secret=$(client_secret)"'
    allowTelemetryCollection: true