trigger: none

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendAzureRmResourceGroupName: 'visal-resourec-group'
    backendAzureRmStorageAccountName: 'visalstorage'
    backendAzureRmContainerName: 'visalreg'  
